---
mysql_server_id: 1
mysql_replication_role: "master"
mysql_expire_logs_days: 10
mysql_max_binlog_size: "100M"
mysql_binlog_format: "ROW"

mysql_databases:
  # binlog_ignore_db
  - name: mysql
    replicate: 99
#   - name: example
#     collation: utf8_general_ci
#     encoding: utf8
#     replicate: 1

keepalived_role: "master"
keepalived_priority: "100"
