---
mysql_replication_master: true
mysql_server_id: 1
mysql_replication_role: "master"
mysql_expire_logs_days: 10
mysql_max_binlog_size: "100M"
mysql_binlog_format: "ROW"

mysql_databases: []
#   - name: example
#     collation: utf8_general_ci
#     encoding: utf8
#     replicate: 1

