---
- name: Install keepalived
  yum: name=keepalived state=present

- name: Configure keepalived
  template:
    src: keepalived.conf.j2
    dest: /etc/keepalived/keepalived.conf
    owner: root
    group: root
    mode: 0644
    force: yes
  notify: restart keepalived

- name: Create directory for keepalived scripts
  file:
    path: "{{ keepalived.script_path }}"
    state: directory
    owner: "{{ keepalived.user }}"
    group: "{{ keepalived.group }}"

- name: Copy keepalived scripts
  copy:
    src: "{{ item }}"
    dest: "{{ keepalived.script_path }}{{ item }}"
    owner: "{{ keepalived.user }}"
    group: "{{ keepalived.group }}"
    mode: 0744
    force: yes
  with_items:
    - keepalived_healthcheck.sh

- name: Copy keepalived scripts from templates
  template:
    src: "{{ item }}.j2"
    dest: "{{ keepalived.script_path }}{{ item }}"
    owner: "{{ keepalived.user }}"
    group: "{{ keepalived.group }}"
    mode: 0744
    force: yes
  with_items:
    - keepalived_to_be_master.sh
    - keepalived_to_be_fault.sh

- name: Ensure keepalived is started and enabled on boot
  service: name=keepalived state=started enabled=yes

