mysql_57:
  global_config_file: /etc/my.cnf
  global_config_dir: /etc/my.cnf.d
  slow_query_log_file: /var/log/mysql-slow.log
  log_error: /var/log/mysql.err
  syslog_tag: mysql
  pid_file: /var/run/mysqld/mysqld.pid
  datadir: /var/lib/mysql
  socket: /var/lib/mysql/mysql.sock
  port: 3306
  support_innodb_large_prefix: false
  default_config: /root/.my.cnf

  # Memory settings (default values optimized ~512MB RAM).
  key_buffer_size: "256M"
  max_allowed_packet: "64M"
  table_open_cache: "256"
  sort_buffer_size: "1M"
  read_buffer_size: "1M"
  read_rnd_buffer_size: "4M"
  myisam_sort_buffer_size: "64M"
  thread_cache_size: "8"
  query_cache_size: "16M"
  query_cache_limit: "1M"
  max_connections: "151"
  tmp_table_size: "16M"
  max_heap_table_size: "16M"


  # Other settings.
  lower_case_table_names: "0"
  wait_timeout: "28800"

  # InnoDB settings.
  innodb_file_per_table: "1"
  # Set .._buffer_pool_size up to 80% of RAM but beware of setting too high.
  innodb_buffer_pool_size: "256M"
  # Set .._log_file_size to 25% of buffer pool size.
  innodb_log_file_size: "64M"
  innodb_log_buffer_size: "8M"
  innodb_flush_log_at_trx_commit: "1"
  innodb_lock_wait_timeout: "50"

  # These settings require MySQL > 5.5.
  innodb_large_prefix: "1"
  innodb_file_format: "barracuda"

  # mysqldump settings.
  mysqldump_max_allowed_packet: "64M"


  config_include_files: []
  #  - src: path/relative/to/playbook/file.cnf
  #  - { src: path/relative/to/playbook/anotherfile.cnf, force: yes }

  # mysql_config_include_dir: /etc/my.cnf.d

  # replication
  replication_master: "10.10.10.1"
  replication_user:
    name: "repl"
    host: "10.10.10.0/255.255.255.0"
    password: "Change_here@1"
    priv: "*.*:REPLICATION SLAVE"
  replication_channel: "CHANNEL_TO_db01"
  expire_logs_days: 10
  max_binlog_size: "100M"
  binlog_format: "ROW"

  failover_user:
    name: "failover"
    host: "10.10.10.0/255.255.255.0"
    password: "Change_here@1"
    priv: "*.*:ALL"

  test:
    db: foo
    user: hoge
    pass: hoge

keepalived:
  auth_pass: "change_here"
  router_id: "100"
  shared_iface: "eth0"
  shared_ip: "10.10.10.7"

mha:
  user: "vagrant"
  group: "vagrant"
  workdir: "/var/tmp/masterha/test"

