---
- name: Remove mariadb
  yum: name=mariadb-libs state=removed

- name: Remove old existing configuration
  file:
    path: "{{ mysql_57.global_config_file }}"
    state: absent

- name: Register mysql's repository
  yum:
    name: http://dev.mysql.com/get/mysql57-community-release-el6-9.noarch.rpm
    state: present

- name: Install mysql
  yum:
    name: "{{ item }}"
    enablerepo: mysql57-community
    state: present
  with_items:
    - mysql-community-server
    - mysql-community-client
    - mysql-community-common
    - mysql-community-libs
    - mysql-community-libs-compat
    - mysql-utilities

- name: Setting mysql auto starting
  service: name=mysqld state=started enabled=yes

- name: Install parckage for ansible mysql modules
  yum:
    name: "{{ item }}"
    state: latest
  with_items:
    - epel-release
    - MySQL-python
    - libselinux-python

- name: Install parckage for ansible pip module
  yum:
    name: "{{ item }}"
    state: latest
  with_items:
    - python-pip
    - python-virtualenv

- name: Install python module for ansible expect module
  pip: name=pexpect state=latest
