---
- name: remove mariadb
  yum: name=mariadb-libs state=removed

- name: upgrade all packages
  yum: name=* state=latest


- name: register mysql's repository
  yum:
    name: http://dev.mysql.com/get/mysql57-community-release-el6-9.noarch.rpm
    state: present

- name: install mysql
  yum:
    name: "{{ item }}"
    enablerepo: mysql57-community
    state: present
  with_items:
    - mysql-community-server
    - mysql-community-client
    - mysql-community-common
    - mysql-community-libs
    - mysql-community-libs-compat

- name: setting mysql auto starting
  service: name=mysqld state=started enabled=yes

- name: install parckage about mysql for ansible mysql modules
  yum:
    name: "{{ item }}"
    state: present
  with_items:
    - MySQL-python
    - libselinux-python
