---
- name: Ensure replication user exists on master.
  mysql_user:
    name: "{{ mysql_57.replication_user.name }}"
    host: "{{ mysql_57.replication_user.host | default('%') }}"
    password: "{{ mysql_57.replication_user.password }}"
    priv: "{{ mysql_57.replication_user.priv | default('*.*:REPLICATION SLAVE') }}"
    state: present
  when: >
    mysql_replication_role == 'master'

#- name: Check slave replication status.
#  mysql_replication: mode=getslave
#  ignore_errors: true
#  register: slave
#  when: >
#    mysql_replication_role == 'slave'
#
#- name: Check master replication status.
#  mysql_replication: mode=getmaster
#  delegate_to: "{{ mysql_57.replication_master }}"
#  register: master
#  when: >
#    mysql_replication_role == 'slave'
#
## mysql_replication module does not support multi-source replication (@2016-11-09)
#- name: Configure replication on the slave.
#  mysql_replication:
#    mode: changemaster
#    master_host: "{{ mysql_57.replication_master }}"
#    master_user: "{{ mysql_57.replication_user.name }}"
#    master_password: "{{ mysql_57.replication_user.password }}"
#    master_log_file: "{{ master.File }}"
#    master_log_pos: "{{ master.Position }}"
#    master_connect_retry: 10
#  ignore_errors: True
#  with_items: "{{ groups.master }}"
#  when: >
#    mysql_replication_role == 'slave'
#
#- name: Start replication.
#  mysql_replication: mode=startslave
#  when: >
#    mysql_replication_role == 'slave'
